### ISSUE TITLE
头文件没有

### ISSUE THREAD

**Issue by command-z-z** [lixy123/t_watch2020_remote_mic#1]
请问 # include <WebSocketsServer>头文件在哪里？

**Comment by lixy123** [comment]
全部源码都有放在
https://github.com/lixy123/ESP32_Remote_MIC/tree/master/esp32/esp32_remote_mic2


你指的是什么头文件？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lixy123/t_watch2020_remote_mic"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月9日(星期四) 下午4:05
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[lixy123/t_watch2020_remote_mic] 头文件没有 (Issue #1)





 
请问 # include 头文件在哪里？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
